// arquivo: tables.js
import bcrypt from "bcryptjs";

// Gera o hash da senha "teste"
const hash = bcrypt.hashSync("teste", 10);

export const tables = {
  user: `
    CREATE TABLE IF NOT EXISTS users (
      id INT AUTO_INCREMENT PRIMARY KEY,
      nome VARCHAR(100) NOT NULL,
      email VARCHAR(100) NOT NULL UNIQUE,
      senha VARCHAR(255) NOT NULL
    );
  `,

  schools: `
    CREATE TABLE IF NOT EXISTS schools (
      id INT NOT NULL AUTO_INCREMENT,
      nomedep VARCHAR(255) DEFAULT NULL,
      de VARCHAR(255) DEFAULT NULL,
      mun VARCHAR(255) DEFAULT NULL,
      distr VARCHAR(255) DEFAULT NULL,
      nomesc VARCHAR(255) DEFAULT NULL,
      tipoesc_desc VARCHAR(255) DEFAULT NULL,
      codesc VARCHAR(50) DEFAULT NULL,
      tipoesc VARCHAR(10) DEFAULT NULL,
      codsit VARCHAR(50) DEFAULT NULL,
      salas_aula INT DEFAULT NULL,
      salas_ed_inf INT DEFAULT NULL,
      salas_ed_esp INT DEFAULT NULL,
      salas_ed_art INT DEFAULT NULL,
      sala_recurso INT DEFAULT NULL,
      tot_salas_aula INT DEFAULT NULL,
      auditorio INT DEFAULT NULL,
      anfiteatro INT DEFAULT NULL,
      teatro INT DEFAULT NULL,
      cantina INT DEFAULT NULL,
      copa INT DEFAULT NULL,
      cozinha INT DEFAULT NULL,
      refeitorio INT DEFAULT NULL,
      deposito_alimentos INT DEFAULT NULL,
      despensa INT DEFAULT NULL,
      tot_despensa INT DEFAULT NULL,
      sala_leitura INT DEFAULT NULL,
      biblioteca INT DEFAULT NULL,
      tot_sala_leitura INT DEFAULT NULL,
      quadra_coberta INT DEFAULT NULL,
      quadra_descoberta INT DEFAULT NULL,
      ginasio INT DEFAULT NULL,
      tot_quadra INT DEFAULT NULL,
      quadra_areia INT DEFAULT NULL,
      quadra_grama INT DEFAULT NULL,
      campo_futebol INT DEFAULT NULL,
      gabinete_dentario INT DEFAULT NULL,
      consultorio_medico INT DEFAULT NULL,
      enfermaria INT DEFAULT NULL,
      ambulatorio INT DEFAULT NULL,
      almoxarifado INT DEFAULT NULL,
      arquivo INT DEFAULT NULL,
      reprografia INT DEFAULT NULL,
      sala_gremio INT DEFAULT NULL,
      diretoria INT DEFAULT NULL,
      vicediretoria INT DEFAULT NULL,
      sala_prof INT DEFAULT NULL,
      secretaria INT DEFAULT NULL,
      sala_orient_ed INT DEFAULT NULL,
      sala_coord_pedag INT DEFAULT NULL,
      patio_coberto INT DEFAULT NULL,
      patio_descoberto INT DEFAULT NULL,
      zeladoria INT DEFAULT NULL,
      vestiario_fem INT DEFAULT NULL,
      vestiario_masc INT DEFAULT NULL,
      tot_vestiario INT DEFAULT NULL,
      videoteca INT DEFAULT NULL,
      sala_tv INT DEFAULT NULL,
      lab_info INT DEFAULT NULL,
      lab_ciencias INT DEFAULT NULL,
      lab_fisica INT DEFAULT NULL,
      lab_quimica INT DEFAULT NULL,
      lab_biologia INT DEFAULT NULL,
      lab_ciencia_fisica_biologica INT DEFAULT NULL,
      tot_lab_ciencia INT DEFAULT NULL,
      lab_linguas INT DEFAULT NULL,
      lab_multiuso INT DEFAULT NULL,
      oficina INT DEFAULT NULL,
      playground INT DEFAULT NULL,
      dormitorio INT DEFAULT NULL,
      bercario INT DEFAULT NULL,
      sanitario_adeq_pre INT DEFAULT NULL,
      sanitario_adeq_pre_fem INT DEFAULT NULL,
      sanitario_adeq_pre_masc INT DEFAULT NULL,
      sanitario_adeq_def INT DEFAULT NULL,
      sanitario_adeq_def_fem INT DEFAULT NULL,
      sanitario_adeq_def_masc INT DEFAULT NULL,
      sanitario_al_masc INT DEFAULT NULL,
      sanitario_al_fem INT DEFAULT NULL,
      tot_sanitario_al INT DEFAULT NULL,
      sanitario_func_fem INT DEFAULT NULL,
      sanitario_func_masc INT DEFAULT NULL,
      tot_sanitario_func INT DEFAULT NULL,
      depend_adeq_def INT DEFAULT NULL,
      sala_ed_fisica INT DEFAULT NULL,
      piscina INT DEFAULT NULL,
      portaria INT DEFAULT NULL,
      sala_prog_esc_familia INT DEFAULT NULL,
      brinquedoteca INT DEFAULT NULL,
      fraldario INT DEFAULT NULL,
      lactario INT DEFAULT NULL,
      lavanderia INT DEFAULT NULL,
      solario INT DEFAULT NULL,
      sala_espera INT DEFAULT NULL,
      sala_inspetor INT DEFAULT NULL,
      sala_reuniao INT DEFAULT NULL,
      tesouraria INT DEFAULT NULL,
      sala_reforco INT DEFAULT NULL,
      sala_diretor_tecnico INT DEFAULT NULL,
      garagem_onibus INT DEFAULT NULL,
      sala_fisioterapia INT DEFAULT NULL,
      sala_psicologia INT DEFAULT NULL,
      sala_fonoaudiologia INT DEFAULT NULL,
      sala_eventos INT DEFAULT NULL,
      sala_assist_social INT DEFAULT NULL,
      sala_terapia_educ INT DEFAULT NULL,
      abatedouro INT DEFAULT NULL,
      alojamento_fem INT DEFAULT NULL,
      alojamento_masc INT DEFAULT NULL,
      tot_alojamento INT DEFAULT NULL,
      area_servico INT DEFAULT NULL,
      bazar INT DEFAULT NULL,
      casa_maquina INT DEFAULT NULL,
      casa_func INT DEFAULT NULL,
      churrasqueira INT DEFAULT NULL,
      depositos_cereais INT DEFAULT NULL,
      elevador INT DEFAULT NULL,
      estacionamento INT DEFAULT NULL,
      estufa INT DEFAULT NULL,
      grafica INT DEFAULT NULL,
      horta INT DEFAULT NULL,
      lab_didatica INT DEFAULT NULL,
      lab_junior INT DEFAULT NULL,
      lab_enfermagem INT DEFAULT NULL,
      lab_estetica INT DEFAULT NULL,
      lab_psicopedagogia INT DEFAULT NULL,
      lab_turismo INT DEFAULT NULL,
      lavanderia2 INT DEFAULT NULL,
      viveiro INT DEFAULT NULL,
      quiosque INT DEFAULT NULL,
      PRIMARY KEY (id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
  `,

  userSeed: `
    INSERT INTO users (nome, email, senha)
    VALUES ('admin', 'admin@teste.com', '${hash}');
  `
};
